import { createApp } from "vue";
import "./assets/style/global.less";
import router from "./router/index";
import App from "./App.vue";
import { store } from "./store";
import HpInput from "./components/HpInput.vue";
import HpButton from "./components/HpButton.vue";
import HpUpload from "./components/HpUpload.vue";
import HpDialog from "./components/HpDialog.vue";
import HpPopover from "./components/HpPopover.vue";
import HpForm from "./components/HpForm.vue";
import HpFormItem from "./components/HpFormItem.vue";
import HpSelect from "./components/HpSelect.vue";

const app = createApp(App);
app.use(store);
app.component("HpInput", HpInput);
app.component("HpButton", HpButton);
app.component("HpUpload", HpUpload);
app.component("HpDialog", HpDialog);
app.component("HpPopover", HpPopover);
app.component("HpForm", HpForm);
app.component("HpFormItem", HpFormItem);
app.component("HpSelect", HpSelect);
app.use(router);
app.mount("#app");
